### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by barthalion** [flathub/org.kde.index#1]
The first build failed: https://flathub.org/builds/#/builders/45/builds/3624 :see_no_evil: 

```
builddir/files/share/appdata/org.kde.index.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> width (1048) did not match specified (2899) [https://invent.kde.org/websites/product-screenshots/-/raw/master/index/index.png]
• attribute-invalid     : <screenshot> height (631) did not match specified (2326) [https://invent.kde.org/websites/product-screenshots/-/raw/master/index/index.png]
```

These URLs should ideally include a commit hash. GitHub converts current URL when one presses `y` so maybe GitLab does too.

**Comment by travier** [comment]
@ognarb

**Comment by ognarb** [comment]
Actually, these urls were wrong, using invent.kde.org raw urls is explicitly discouraged (because it can add a big load on our gitlab instance) and they should have used cdn.kde.org. I changed it and added a few more screenshots at the same time. Versioning the screenshots could be a good idea in the future so that this doesn't happens again.

**Comment by barthalion** [comment]
@ognarb FWIW we mirror all screenshots and serve them from Flathub CDN, so the only request reaching invent.kde.org should be the one coming from a builder machine.

**Comment by ognarb** [comment]
@barthalion Yeah but the screenshots are also displayed on https://apps.kde.org/index-fm/ and we don't mirror the screenshots there (since we assume all KDE software are using cdn.kde.org/screenshots for their appstream screenshots)
